### ISSUE TITLE
Enhancement: CAP Grids

### ISSUE THREAD

**Issue by postalservice14** [apps4av/avare#105]
Would love to see the CAP Grids as some sort of layer over the sectional.  See http://www.cap-es.net/CAPGrids/Conventional%20Grid%20System.htm for more info.

FltPlan Go, FlightPro and ForeFlight all have it and is very useful for Civil Air Patrol pilots.

**Comment by apps4av** [comment]
http://www.cap-es.net/CAPGrids/Conventional%20Grid%20System.htm

**Comment by postalservice14** [comment]
Work in progress, but made some pretty good modifications tonight: https://github.com/postalservice14/avare/tree/cap_grids

Gotta work on the grid labels.  Pinch zooming makes them scale all weird.  Then I need to add the other charts.  Right now only SEA is available (just for development).  Gettin' there...

**Comment by apps4av** [comment]
There are some drawing issues. Sometimes when panning the grid disappears. See the attached pictures. 
Also, if possible please add comments to the code. 
Targeted for beta release next week, and public release 6.0.7 at the end of the month.

![screenshot from 2015-05-14 14 53 09](https://cloud.githubusercontent.com/assets/2947279/7639352/2ef84686-fa49-11e4-9e59-bc4e96e78c89.png)
![screenshot from 2015-05-14 14 53 32](https://cloud.githubusercontent.com/assets/2947279/7639357/33838d0a-fa49-11e4-81ec-896babf96820.png)

**Comment by apps4av** [comment]
More comments from the reviewers on the coding side:
- entire preferences.xml has changed, making it hard to see the changes. may tabs issue
- looks really calc intensive during the draw (use init/ctor call for that as much as psble)
- draw should just bail when mService == null (first check)
- getCapCharts() on each draw looks slow -- do that calc during an origin or gps change
- comments comments comments

**Comment by apps4av** [comment]
fixed and on head. code from postalservice14 was combined with new code to draw this efficiently
