### ISSUE TITLE
CDI too sensitive close to the airport

### ISSUE THREAD

**Issue by apps4av** [apps4av/avare#119]
Have done some more testing of the CDI feature with multi-leg flight plans using version 6.0.4 and have noticed something odd. When approaching a way point the displayed graphic CDI on the screen seems to become overly sensitive and jerky, jumping back and forth sometimes full scale as if the sensitivity might be a thousandth of a mile or worse. Maybe there is some kind of rounding error. This is most apparent when about a mile or less from the way point either inbound or outbound. Both the digital CDI in the dynamic field display and the autopilot output stay steady.

**Comment by N520TX** [comment]
revision 1522. fix some data types to minimize chance of rounding and type conversion
