### ISSUE TITLE
Port project to Android Studio?

### ISSUE THREAD

**Issue by postalservice14** [apps4av/avare#132]
@apps4av Are you interested in porting this project over to an Android Studio project, since the Eclipse ADT is no longer supported?

I can create a PR for it if you'd like.

**Comment by apps4av** [comment]
Will check the Cap tonight and then merge for next release, unless some
issues found.

Regarding AS, we will have to talk internally about this. We have tried
once before to use AS, and it disappointed us a lot. Maybe its better now.





On Wed, May 13, 2015 at 7:58 PM, John Kelly <notifications@github.com>
wrote:

> @apps4av <https://github.com/apps4av> Are you interested in porting this
> project over to an Android Studio project, since the Eclipse ADT is no
> longer supported?
>
> I can create a PR for it if you'd like.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apps4av/avare/issues/132>.
>



-- 
Zubair Khan
apps4av.com
zk4u.blogspot.com
Sudbury, MA 01776

**Comment by postalservice14** [comment]
I really quickly used the AS importer and ran the app from AS after importing, and it seemed to work great.  Not sure what issues you ran into before.

**Comment by apps4av** [comment]
We had the AS crash, hang, debugging wrong line, auto fill incorrectly etc.
I hope all these issues are fixed. I suggest playing with it a bit then
reporting back.

On Thu, May 14, 2015 at 10:09 AM, John Kelly <notifications@github.com>
wrote:

> I really quickly used the AS importer and ran the app from AS after
> importing, and it seemed to work great. Not sure what issues you ran into
> before.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apps4av/avare/issues/132#issuecomment-102047417>.
>



-- 
Zubair Khan
apps4av.com
zk4u.blogspot.com
Sudbury, MA 01776

**Comment by postalservice14** [comment]
I've played around with Avare after porting it over...

I tried debugging, a couple of different virtual devices (and real devices).  It never crashed for me, and was awesome to work with.

I use Android Studio for my other projects and love it.  Haven't had any trouble with it.  So maybe the issues you've had in the past have been resolved.

**Comment by apps4av** [comment]
Done
