### ISSUE TITLE
values/arrays.xml has inconsistent value on TimerRingSize{Values, Prompt}

### ISSUE THREAD

**Issue by wenyu** [apps4av/avare#141]
<string-array name="TimerRingSizeValues">
        <item>0</item>
        <item>1</item>
        <item>5</item>
        <item>10</item>
    </string-array>
....
    <string-array name="TimerRingSizePrompt">
        <item>None</item>
        <item>2 Minutes</item>
        <item>5 Minutes</item>
        <item>10 Minutes</item>
    </string-array>

**Comment by N520TX** [comment]
Corrected rev 1570
