### ISSUE TITLE
Draw mode not working on Nexus 5

### ISSUE THREAD

**Issue by nickdavies** [apps4av/avare#146]
When I switch between draw and pan mode both pan instead of drawing and draw mode is missing the erase button.

Phone model: Nexus 5
App Version: 6.0.9
Android Version: 4.4.4

![screenshot_2015-07-10-11-01-37](https://cloud.githubusercontent.com/assets/118736/8625396/5c6d6ef8-26f3-11e5-9e6d-68fbeb6ef610.png)
![screenshot_2015-07-10-11-01-42](https://cloud.githubusercontent.com/assets/118736/8625397/5c6d8dd4-26f3-11e5-8d37-ed6438afb39a.png)

**Comment by nickdavies** [comment]
This could quite easily be user error as I just started using the app. If you need anymore info let me know

**Comment by avcomware** [comment]
Hi Nick.I was unable to duplicate your problem. 
You may want to try and see if it does the same thing in Portrait or Landscape, Not Sensor? It works on my devices if I have the Display>Screen orientation set to either Portrait or Landscape or Sensor.Sensor Mode can do some strange things.
If problem continues post on:https://groups.google.com/forum/#!forum/apps4av-forumfor others to see and respond.
You may want to try and see if it does the same thing in Portrait or Landscape, Not Sensor? It works for my devices if I have the Display>Screen orientation set to either Portrait or Landscape or Sensor.Sensor Mode can do some strange things. TV

>>When I switch between draw and pan mode both pan instead of drawing and draw mode is missing the erase button.Phone model: Nexus 5
App Version: 6.0.9
Android Version: 4.4.4<<

**Comment by apps4av** [comment]
This was in Track Up. North Up was fine. Fixed.
