### ISSUE TITLE
TFR shading is orange and not very visible. Suggest reverting shape shading

### ISSUE THREAD

**Issue by xargsgrep** [apps4av/avare#202]

**Comment by r-oleary** [comment]
I actually quite like the shading. Check out latest master to see what the TFR looks like with shading + stroke. If you still don't like it, I'll move it to a Preference

**Comment by apps4av** [comment]
Will check with Ahsan's changes when complete.

**Comment by xargsgrep** [comment]
added preference for TFR shading

https://github.com/apps4av/avare/commit/8920a70b0cef686b11b7eead2dbf800506b7fe09
