### ISSUE TITLE
Disable autocorrect in flight plan entry box

### ISSUE THREAD

**Issue by henryhallam** [apps4av/avare#216]
Android autocorrect likes to change KEMT to 'Kent', DOCAL to 'social' etc...

I'm no android developer, but it seems like this is possible: http://stackoverflow.com/questions/3799840/edittext-without-auto-correction-etc

**Comment by apps4av** [comment]
Its been tried many times and it has no solution to date on android. Best
way to do this is to disable IME input text corrections in Android input
settings, pr samsung keyboard settings.
