### ISSUE TITLE
name not displayed/lost in name@lat&lon waypoint

### ISSUE THREAD

**Issue by pasniak** [apps4av/avare#222]
Display "name" (in "name@lat&lon"-style waypoint) is (not displayed) when long-pressing a such named waypoint - only "lat&lon" is displayed. Also, the name is "lost" when moving/dragging (even slightly) a named waypoint.

Example:
1) Add (type) new waypoint to a plan: http://i.imgur.com/UEyeNyn.png
2) Long press on this waypoint on the map: http://i.imgur.com/uCKhTkJ.png
3) Reposition the waypoint on the map: http://i.imgur.com/bJw9ta7.png

**Comment by apps4av** [comment]
Unable to reproduce. Closing.

**Comment by apps4av** [comment]
Unable to reproduce. Closing.
