### ISSUE TITLE
Decoding METAR small issues

### ISSUE THREAD

**Issue by pasniak** [apps4av/avare#228]
https://i.imgur.com/N4rB3rC.png

"KWRI the always-Wet-Runway airport"

+ there are some grammar corrections in the decoding code.

**Comment by apps4av** [comment]
That's funny :)

**Comment by pasniak** [comment]
another one https://i.imgur.com/2arf4wV.png

**Comment by apps4av** [comment]
Yes same issue. The ID should be taken out of translation routine.

**Comment by pasniak** [comment]
see PR #230
