### ISSUE TITLE
possible to lose tabs behind soft keyboard switching from Find

### ISSUE THREAD

**Issue by pballer2oo7** [apps4av/avare#266]
1. switch to Find tab
2. tab search textfield to pull up soft keyboard
3. tab bar appears above soft keyboard, tap Map

the tab bar goes back to the bottom of the screen, hidden behind the soft keyboard which does 

![02](https://cloud.githubusercontent.com/assets/7807540/22002642/d6f98916-dc4d-11e6-86ba-9654fcf00711.png)
![03](https://cloud.githubusercontent.com/assets/7807540/22002641/d6f94bfe-dc4d-11e6-9f50-9e1e12ba654d.png)
![01](https://cloud.githubusercontent.com/assets/7807540/22002643/d6fa7eca-dc4d-11e6-9185-b4ed7ffedf0c.png)

not dismiss

**Comment by reddn** [comment]
Isn't this normal android behavior.

**Comment by pballer2oo7** [comment]
we should be dismissing the keyboard, if it's open, when we change to Map tab

**Comment by apps4av** [comment]
Fixed release 7.6.6.
