### ISSUE TITLE
Rename Preference "Use Label for METARs"

### ISSUE THREAD

**Issue by pasniak** [apps4av/avare#269]
This option is confusing as it has NO effect unless METARs are pulled from ADSB.

I propose to rename it "Use Label for ADSB Weather METARs" with summary "Select to choose between circles or labeled METAR indicators when using ADSB Weather"

**Comment by pasniak** [comment]
https://i.imgur.com/EiZd28I.png

**Comment by apps4av** [comment]
Renamed, closing.
