### ISSUE TITLE
Logo Designer

### ISSUE THREAD

**Issue by dibon-github** [apps4av/avare#321]
Good day, I would be willing to collaborate and make a new logo design for your app. Pls do reply if you accept my offer. I do work for free, dont worry sir. I would do anything for the benefit of this project.

**Comment by apps4av** [comment]
Hello
Thanks for the offer. What do you have in mind and why is the current logo
not acceptable?

**Comment by dibon-github** [comment]
I do have something in mind, a modern approach for your logo because it looks a bit old. Would you mind giving me a chance to give you a design tomorrow? and see If it fits your project?

**Comment by reddn** [comment]
In this guys defense, he may be only looking at the play store icon, and
not the launcher icon, which are different.

See attached baa

**Comment by reddn** [comment]
I do think Avare should change the play store icon to the launcher icon.

**Comment by reddn** [comment]
Sorry for the multiple emails.  Need to clarify what I said, it sounded
right in my head when I first typed it.

I think Avare should make the play store icon the same as the current
launcher icon.

**Comment by dibon-github** [comment]
yah maybe sir, thanks for clarifying that to me

**Comment by dibon-github** [comment]
if ever you need help for anything feel free to contact me

**Comment by apps4av** [comment]
Hello baa
Please describe what you want in the new icon. Our icon is our identity but
if you have a great idea we want to hear about it.
Thanks for offering.

**Comment by JohnW4SBA** [comment]
> a modern approach for your logo

I'd like to see that and I very much appreciate your offer, but I'm 
unclear.  Is there some reason you might prefer not to design a new logo 
unless you are assured in advance that it will be used?

Might you be willing to provide some rough samples that could be created 
while minimizing your effort, so that others here could provide feedback 
or requests that you could consider for implementation?

**Comment by dibon-github** [comment]
![image](https://user-images.githubusercontent.com/31919065/38300741-34380e1a-3830-11e8-9377-6b3ca0fe0429.png)
this is whats appearing upon clicking the link. Pls just send the image of your current logo. And Ill do make a design and send it tomorrow. It doenst matter if it gets used or not. Ill just do my best and see if I suite your taste.

**Comment by dibon-github** [comment]
![dffsdffds](https://user-images.githubusercontent.com/31919065/38300886-a146aab6-3830-11e8-9f00-026a5927e9f2.PNG)
this is whats appearing upon clicking the link. Pls just send the image of your current logo. And Ill do make a design and send it tomorrow. It doenst matter if it gets used or not. Ill just do my best and see if I suite your taste.

**Comment by dibon-github** [comment]
At first the logo I saw on your playstore was I thinking, not knowing that your current launcher icon is different from the logo displayed here. sorry for that misunderstanding.
![image](https://user-images.githubusercontent.com/31919065/38301083-1c3936da-3831-11e8-93b5-b2084d5f59d8.png)

**Comment by gustafson** [comment]
Marking as closed as the originator appears satisfied.
