### ISSUE TITLE
Drawing on a plate doesn't stay when panning

### ISSUE THREAD

**Issue by caseyvanburen** [apps4av/avare#323]
When making a drawing on the plate tab, for example an airport diagram, if I switch back to pan and do anything (move around, zoom in or out) the drawing stays where it is and the map moves around underneath it.

![ezgif-4-36ea8dc5ba](https://user-images.githubusercontent.com/5621169/41383784-70fb17ce-6f40-11e8-8e8c-34133bd58a27.gif)

Device:
Nexus 7, android version 6.0.1

**Comment by caseyvanburen** [comment]
Probably what #273 is referring to.

**Comment by danothemen** [comment]
#328 Should fix this
