### ISSUE TITLE
Listen option on IO tab should be "sticky"

### ISSUE THREAD

**Issue by n251ea** [apps4av/avare#447]
Every time Avare is restarted in order to receive ADS-B data you must go to the IO tab and check the "listen" box in order to receive ADS-B traffic.  The Listen box should be sticky (remains checked) so that it remains selected after an Avare restart.
![IO](https://user-images.githubusercontent.com/48159367/162637179-cc082a8e-7041-4138-9b35-bce80653d9c9.jpg)

**Comment by apps4av** [comment]
Fixed
