### ISSUE TITLE
Dual XGPS160 Stopped working for 10.2.0 10.2.1 10.2.2

### ISSUE THREAD

**Issue by nicholascw** [apps4av/avare#478]
Setup tested to be working fine with 10.1.9 from APKPure;

With 10.2.2 from Play Store and F-Droid: on Map tab, reads red "No GPS Signal" on top-left, despite of GPS coordinates spitting out on I/O tab after connecting the Bluetooth.

**Comment by apps4av** [comment]
Try app 10.2.3. From apps4av.org/share site, or from play store when
available.

**Comment by nicholascw** [comment]
Thanks. 10.2.3 from apps4av.org/share appear to be working fine.
