### ISSUE TITLE
Unable to update database

### ISSUE THREAD

**Issue by xxxxme** [apps4av/avare#510]
When attempting to download/update maps, this fails with the message, "Download Failed: databases, code unable to download the file from this cycle".

Avare 10.3.2.328 from F-Droid
LineageOS 20 (A14) on Pixel 5a
Also happens on Samsung SM-T870 w/ OneUI 5.1.1 (A13).
Happens on wifi and cellular data.

**Comment by apps4av** [comment]
Version 11 is the latest. Update to it to get charts.

**Comment by xxxxme** [comment]
Installed version 11. Now when zooming in, the app demands, "Download Sectional Chicago" (for example), but that's no longer an option in the download menu. "North Central" *is* downloaded.

**Comment by n251ea** [comment]
These questions should be on the mailing list not GitHub and has been answered there previously.

The reason you are getting the error is because Chicago is in the East Central charts,  we are using the same division that the FAA uses for the chart supplements.
