### ISSUE TITLE
Skip missed waypoints, and smooth out the autopilot turn

### ISSUE THREAD

**Issue by apps4av** [apps4av/avare#78]
Reported: Currently unable to skip the missed waypoints on the Plan screen.

A button that would advance to the next waypoint with every push. You could skip one or many. Plus by advancing the waypoint right before a waypoint a coupled autopilot could do a nice turn and intercept the new course without overshooting (a feature that could also be done automatically by AVARE).

**Comment by N520TX** [comment]
This is addressed via the plan control buttons. They are accessible on the PLAN tab or the MAP tab if "Show Flight Plan Controls" is enabled.
