### ISSUE TITLE
CDI not working on waypoints in Plan

### ISSUE THREAD

**Issue by apps4av** [apps4av/avare#83]
TV:
![unnamed](https://cloud.githubusercontent.com/assets/2947279/3437505/d3c206d0-00b1-11e4-95fa-314c67e290c8.jpg)

Summary of it is, that after you pass a Waypoint that is Not an Airport or Destination the Colors and Arrowhead point in the wrong direction, to what seems to be a Direct course from Airport A (KSNA) to Airport B (KTOA) in this case, or somewhat close, but not exactly. See Section -Pic. 4 that has the Track / .kml (black line) and the Direct course from SNA>TOA. The Headings in the Text Flight Plan (text generated by Plan) show proper values.
 
In section Pic. 1, All OK, Color, Arrowhead, Acft. Position with respect to Course line.
In section Pic. 2 Wrong Color (should be Gray / Green) and Arrow direction, after passing ALBAS.
In section Pic. 3 Deviation required to get centered (GREEN in my case), see the .kml black track line.
In Section Pic. 4 shows the location of where the other pics were taken and the track (black line) required to intercept / get within,  the GREEN / center zone and proper Arrow direction indication.
 
As an additional information I did some testing on the devices I have, Samsungs, 4.1.0, 4.1.2 and a LG phone 4.4.2, and observed visible, (3-4x) speed reduction in the chart load, Zoom and over all execution of the app. I am not sure why but the recommendation should be, at least for the slower devices, mine are 1.2GHz dual and 1.2 quad for LG, to use it in the Internal SD card /default location if possible.
I will give you more feedback as soon as I find something that makes sense. TV

**Comment by N520TX** [comment]
As of 6.0.1 CDI now correctly tracks beyond the first waypoint.
