### ISSUE TITLE
Add ability to set default AF/D (text or PDF)

### ISSUE THREAD

**Issue by majdominator** [apps4av/avare#98]
It would be nice to set the default AF/D to PDF. One main reason for this is that many Class Golf airports do not have published airport diagrams. The PDF AF/D does have a diagram. It would be nice that if you click on plates and it's not there, you can quickly go to the AF/D tab and see it. No other drop downs to click on while you're flying.

**Comment by apps4av** [comment]
All airports have airport diagrams in release 6.0.5. Closing
